config/routes.rb
Mobileandroidtraining::Application.routes.draw do

	get "students/new"

	match '/signup', :to => 'students#new'

	

	
	
	match '/instructors', :to => 'pages#instructors'
	match '/courses', :to => 'pages#courses'
 
	match '/thankyou', :to => 'pages#thankyou'
 
	root :to => 'pages#home'

	
	resources :students, :only => [:new, :create, :show]

end

app/models/student.rb
class Student < ActiveRecord::Base
 	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :email, 	:presence => true,
						:format => {:with => email_regex},
						:uniqueness => { :case_sensitive => false} 

	validates :comment, :length => { :maximum => 500 }
		
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		@title = "Android Training Online Android Certificate Learn Android App Development Android Program Class Training Online Certificate Mobile Certification UW University of Washington Android Course Learn Android Continuing Education"

		@meta_keywords = "Android Training Online Home Android Certificate Android Class Learn Android"
		@meta_description = "Sign up page for learning Android at the University of Washington"	
	end



	def instructors 
		@title = "Android Instructors Android Certified Instructor Android Teacher"


		@meta_keywords = "Android Instructors Android Certified Teacher Scott Farrar"
		@meta_description = "Instructors for Learning Android getting Android Certification"	

	end


	def courses
		@title = "Android Courses Mobile Classes Beginning Android Intermediate Android Advanced Android Learn Android Android Entrepreneurship Learn Google TV Course"
	
		@meta_keywords = "Android Courses Mobile Classes Beginning Android Advanced Andorid Learning Android Learn Google TV Course"
		@meta_description = "Courses in University of Washington Android Certification Program"	

	end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.xml
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @students }
    end
  end

  # GET /students/1
  # GET /students/1.xml
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @student }
    end
  end

  # GET /students/new
  # GET /students/new.xml
  def new
    @student = Student.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.xml
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to(@student, :notice => 'Your request was successfully recorded.') }
        format.xml  { render :xml => @student, :status => :created, :location => @student }
		
		StudentMailer.welcome_email(@student).deliver

      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @student.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.xml
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to(@student, :notice => 'Request was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @student.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.xml
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to(students_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Instructors", instructors_path %></li>
      <li><%= link_to "Courses", courses_path %></li>
      <li><a href="http://www.android.com/">Android News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
      <header>
	
<a href="http://www.facebook.com/pages/Certificate-Program-in-Android-Application-Development/190861560932627"><img src="<%= root_path %>images/facebook.png"/></a>

<a href="http://www.linkedin.com/in/scottfarrar"><img src="<%= root_path %>images/linkedin.png"/></a>
<a href="http://www.android.com"> <img src="<%= root_path %>images/android.png"/> </a>

<nav class="round">

          <ul>
            <li><%= link_to "Home", root_path  %></li>
            <li><%= link_to "Instructors", instructors_path %></li>
            <li><%= link_to "Courses",  courses_path %></li>
          </ul>
        </nav>
      </header>

app/views/layouts/_stylesheets.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->    
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= @title %></title>
  
	<meta name="keywords" content="<%= @meta_keywords %>"/>
	<meta name="description" content="<%= @meta_description %>"/>
	
	<%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets' %>


<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21248241-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>


 </head>
 <body>
    <div class="container">

  		<%= render 'layouts/header' %>
		      	

		<section class="round">
      		<%= yield %>
		</section>


	 	<%= render 'layouts/footer'%>
    </div>

   </body>
</html>

app/views/pages/courses.html.erb
<h2>Course 1: Android Development Fundamentals</h2>
<p>This course will introduce the student to the core development skills
and practices needed to develop an application on the Android
platform.  Code examples will be provided during instruction with the
goal of development of an application by the student at the end of the
course.  The language for the course is Java, and students will have a chance to explore various Android device types including handset, tablets and <a href="http://www.google.com/tv/">Google TVs</a>.</p>

<h2>Course 2: Interaction and Communication with Android</h2>
<p>The second course builds on the foundations of Android development. We
will discuss topics on application communications to retrieve and
store data, interaction between other applications, and development
techniques that use advanced features of the Android platform.
Communication and interaction are key concepts to building rich
applications in the Android environment.</p>

<h2>Course 3: Application Deployment, Marketing and Entrepreneurship</h2>
<p>The third course in the Android development series focuses on the
business functions that allow a developer to bring an application to
the appropriate audience. We cover the aspects of application versions
and upgrade management, marketplace hosting, and monitoring tools for
your application.  We will look at the business costs associated with
application hosting and ways to market your application.</p>

app/views/pages/home.html.erb
<center><h1>Become a certified Android App Developer!</h1></center>



<%= link_to "Sign up for more information", 'signup', :class => "signup_button round" %>

<center><h3>The University of Washington is offering a Certificate Program in Android Application Development</h3></center>
<p>
Android just became the <a href="http://www.canalys.com/pr/2011/r2011013.html">world's top selling mobile platform</a>! And the University of Washington’s Professional & Continuing Education Division has developed a new Certificate Program in Android Application Development -- one of only 3 in the country.</p>

<ul>
	<li>Audience: professionals</li>
	<li>Launch Date: Fall 2011</li>
	<li>Where: Seattle and Bellevue, WA</li>
	<li>Online: Yes</li>
	<li>Signup: Begins in June</li>
</ul>  
	<center><h3>Please send me a <%= link_to "sign up", 'signup' %> alert</h3></center>

<p>The Program was developed in conjunction with an Advisory Board consisting of both UW faculty and industry professionals:</p>
<table>
<tr>
<td>Google</td>
<td>Samsung</td>
</tr>
<tr>
<td>T-Mobile</td>
<td>And others...</td>
</tr>


</table>

The goal of the Certificate Program is to provide industry professionals with the core development skills needed to develop an application on the Android platform. In the first two courses, we will cover both beginning and advanced topics. The Program concludes with a course in app publication and mobile app marketing. Students will work on a variety of devices (handsets, tablets and <a href="http://www.google.com/tv/">Google TVs</a>) generously donated by several Board member companies including Google.
</p>

app/views/pages/instructors.html.erb
<h1>Instructors</h1>

<table>
	<tr>
	<td>  <img src="images/farrar.jpg"/> </td>

	<td> <a href="http://faculty.washington.edu/farrar">Scott Farrar</a> PhD,  <a href="mailto:farrar@uw.edu?subject=androidcert">farrar@uw.edu</a>
	<p>Scott received his degree from the University of Arizona and is currently teaching mobile development and NLP in the Computational Linguistics <a href="http://www.compling.uw.edu">Master's Program</a> at the University of Washington. Scott has taught courses in document summarization, dialogue processing, information extraction, and Semantic Web technologies. He has held a number of National Science Foundation research grants in the area of language documentation through the use of technology. He is a freelance Android developer and is currently CTO at <a href="http://broadspeak.com">Broadspeak</a> a social, mobile start-up.</p></td>

</table>

app/views/pages/thankyou.html.erb
<h1> Thank you for signing up for more info!</h1>


<%= link_to 'Home', root_url%>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited request from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	<%= f.label 'E-mail (will not be shared)' %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label 'Prefer the on-line course?' %><br />
    <%= f.check_box :online %>
  </div>
  <div class="field">
    <%= f.label 'comment (optional)' %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit 'submit' %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<!--%= link_to 'Show', @student %--> 
<!--%= link_to 'Back', students_path %-->

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <tr>
    <th>E-mail (will only be used for correspondance about this program)</th>
    <th>Are you interested in taking this course on-line?</th>
    <th>Additional comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.email %></td>
    <td><%= student.online %></td>
    <td><%= student.comment %></td>
    <td><!--%= link_to 'Show', student %--></td>
    <td><!--%= link_to 'Edit', edit_student_path(student) %--></td>
    <td><!--%= link_to 'Destroy', student, :confirm => 'Are you sure?', :method => :delete %--></td>
  </tr>
<% end %>
</table>

<br />

<!--%= link_to 'New Student', new_student_path %-->

app/views/students/new.html.erb
<h1>Send me occasional updates and more information about the program</h1>

<%= render 'form' %>

<!--%= link_to 'Back', students_path %-->

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @student.email %>
</p>

<p>
  <b>Online:</b>
  <%= @student.online %>
</p>

<p>
  <b>Comment:</b>
  <%= @student.comment %>
</p>

<%= link_to 'Home', root_path %>

<!--%= link_to 'Edit', edit_student_path(@student) %--/> |
<!--%= link_to 'Back', students_path %--/>